FROM node:14

# Create app directory
RUN mkdir -p /usr/src/app/frontend
WORKDIR /usr/src/app/frontend

# Install app dependencies
COPY ./frontend .
RUN yarn build
ENV PATH="./node_modules/.bin:${PATH}"

EXPOSE 3000

# Command to run the app
CMD [ "yarn", "start" ]
