version: "3"
services:
  food-finder-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - ENV=local
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
    entrypoint:
      - "/bin/bash"
    container_name: "food-finder-app"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    container_name: "mongo"
