version: "3"
services:
  food-finder-backend-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.backend
    environment:
      - ENV=local
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/backend/node_modules
    entrypoint:
      - "/bin/bash"
    container_name: "food-finder-backend-app"

  food-finder-frontend-app:
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: Dockerfile.frontend
    environment:
      - ENV=local
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/frontend/node_modules
    entrypoint:
      - "/bin/bash"
    container_name: "food-finder-frontend-app"

  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    container_name: "mongo"
