name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker images
      run: |
        docker-compose build
        docker-compose up -d
    - name: Lint frontend and backend with tslint
      run: |
        docker-compose exec -T food-finder-frontend-app node_modules/.bin/tslint --quiet--project .
        docker-compose exec -T food-finder-backend-app node_modules/.bin/tslint --quiet--project .
